DROP TABLE IF EXISTS BookedAttendees;
DROP TABLE IF EXISTS BookedEvents;
DROP TABLE IF EXISTS Attendees;
DROP TABLE IF EXISTS Venues;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Speakers;

CREATE TABLE Speakers (
ID INT UNSIGNED AUTO_INCREMENT,
Name VARCHAR(50) UNIQUE,
Bio VARCHAR(1000),
ContactInfo VARCHAR(100),
PRIMARY KEY(ID)
);

CREATE TABLE Events (
ID INT UNSIGNED AUTO_INCREMENT,
Title VARCHAR(100) UNIQUE,
DateTime DATETIME UNIQUE,
Description VARCHAR(1000),
PRIMARY KEY(ID)
);

CREATE TABLE Venues (
ID INT UNSIGNED AUTO_INCREMENT,
Name VARCHAR(100),
Location VARCHAR(50) UNIQUE,
Capacity INT UNSIGNED,
ContactInfo VARCHAR(100),
PRIMARY KEY(ID)
);

CREATE TABLE Attendees (
ID INT UNSIGNED AUTO_INCREMENT,
Name VARCHAR(50) UNIQUE,
Email VARCHAR(100),
RegistrationDate DATE,
EventAttended VARCHAR(100),
PRIMARY KEY(ID),
FOREIGN KEY (EventAttended) REFERENCES Events(Title)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE BookedEvents (
ID INT UNSIGNED AUTO_INCREMENT,
EventTitle VARCHAR(100),
SpeakerName VARCHAR(50),
VenueLocation VARCHAR(50),
EventDateTime DATETIME,
PRIMARY KEY(ID),
FOREIGN KEY (EventTitle) REFERENCES Events(Title)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY (SpeakerName) REFERENCES Speakers(Name)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY (VenueLocation) REFERENCES Venues(Location)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY (EventDateTime) REFERENCES Events(DateTime)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE BookedAttendees (
EventID INT UNSIGNED,
AttendeeID INT UNSIGNED,
AttendeeName VARCHAR(50),
FOREIGN KEY (EventID) REFERENCES Events(ID)
ON UPDATE RESTRICT
ON DELETE CASCADE,
FOREIGN KEY (AttendeeID) REFERENCES Attendees(ID)
ON UPDATE RESTRICT
ON DELETE CASCADE,
FOREIGN KEY (AttendeeName) REFERENCES Attendees(Name)
ON UPDATE CASCADE
ON DELETE SET NULL
);

INSERT INTO Events (Title, DateTime, Description)
VALUES ('TED Talk', '2024-02-13', 'A short TED talk from an esteemed professor from Lipscomb University');

SELECT * FROM Events;



